ibrary(ape)
library(Biostrings)
library(DECIPHER)
library(seqinr)
library(ade4)
library(viridis)
getwd()
setwd("~/Evidencia2")
corona_virus <-
c("AY278489","AY390556","AY485277","AY508724","JX869059","MN908947","MN985325","MT292571","MT820489","MT845878","MT873893","MT876433","MT919790","MT959161","
MW000351")
virus_sequences<-read.GenBank(corona_virus)
write.dna((virus_sequences),file="coronavirus_seqs.fasta",format="fasta")
virus_seq_not_align <- readDNAStringSet("coronavirus_seqs.fasta",format="fasta")
virus_seq_not_align <- OrientNucleotides(virus_seq_not_align)
virus_seq_align <- AlignSeqs(virus_seq_not_align)
BrowseSeqs(virus_seq_align)
writeXStringSet(virus_seq_align, file="coronavirus_seq_align.fasta")
virus_aligned <- read.alignment("coronavirus_seq_align.fasta", format = "fasta")
matriz_distancia <- dist.alignment(virus_aligned, matrix = "similarity")
temp <- as.data.frame(as.matrix(matriz_distancia))
table.paint(temp, cleg=0, clabel.row=.5, clabel.col=.5) +scale_color_viridis()
virus_tree <- nj(matriz_distancia)
virus_tree <- ladderize(virus_tree)
plot(virus_tree)
